version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-client-java
    steps:
      - checkout
      - restore_cache:
          keys:
            - eventuate-client-java-{{ checksum "gradle.properties" }}
            - eventuate-client-java-
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-client-java-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./gradlew build
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./deploy-artifacts.sh
          when: on_success

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
